test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: interapptive_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: interapptive_prod
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

compilation:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: interapptive_compilation
  pool: 5
  username: root
  password:
  host: 172.16.10.173
  port: 3306
